config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :follows
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main' ,to: 'users#main'
  post 'login' ,to: 'users#login'
  get 'feed/:id' ,to: 'users#feed'
  get 'profile/:name' ,to: 'users#profile'
  get 'profile/:name' ,to: 'users#profile'
  get 'follow/:id' ,to: 'follows#follow'
  get 'unfollow/:id' ,to: 'follows#unfollow'
  get 'like/:id' ,to: 'likes#like'
  get 'unlike/:id' ,to: 'likes#unlike'
end

app/models/user.rb
class User < ApplicationRecord
	has_many :followers, class_name: 'Follow', foreign_key: 'follower_id'
	has_many :followees,  class_name: 'Follow', foreign_key: 'followee_id'
	has_many :posts
	has_many :likes
	has_secure_password
	validates :email, presence: true
	validates :password, presence: true
	def get_feed_post
		pfeed = Array.new
  		listOfFollower = self.followees
  		listOfFollower.each do |follower|
    		tId = follower.follower_id 
    		tUser = User.find_by(id: tId)
    		tUser.posts.each do |post|
      			pfeed.push(post)
    		end
  		end
  		self.posts.each do |post|
    		pfeed.push(post)
  		end
  		pfeed.sort! { |a,b| a.updated_at <=> b.updated_at }.reverse!
  		return pfeed
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :logged_in, except: %i[ index main login new create signup register]
  before_action :is_user, only: %i[ show edit update destroy ]
  before_action :is_nuser, only: %i[ feed ]
  @fLogin = false
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    temp = user_params["email"] 
    tempU = User.find_by(email:temp)
    if tempU != nil
      redirect_to main_path,alert: "Can't use this email"
    else
        respond_to do |format|
          if @user.save
            format.html { redirect_to main_path, notice: "User was successfully created." }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end  
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to "/feed/#{@user.id}", notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def main
    session[:user_id] = nil
    if @fLogin
      @user = User.find_by(email: @email)
    else
      @user = User.new
    end
  end

  def login
    luser = params[:user]
    @email = luser['email']
    @password = luser['password']
    @user = User.find_by(email: @email)
    respond_to do |format|
      if @user != nil 
        if @user.authenticate(@password.to_s)
          session[:user_id] = @user.id
          format.html { redirect_to "/feed/#{@user.id}", notice: "User was successfully updated." }
          format.json { render :showUser, status: :ok, location: @user }
        else 
          @fLogin = true
          format.html { redirect_to main_path, alert: "Wrong password"}
          format.json { render json: @user.errors, status: :unprocessable_entity}
        end
      else
        @fLogin = true
        @user = User.new
        format.html { redirect_to main_path ,alert: "Not found this user"}
        format.json { render json: @user.errors, status: :unprocessable_entity}
      end
    end

    def feed
      id = params[:id]
      @user = User.find_by(id: id)
      @pfeed = @user.get_feed_post
    end

    def profile
    end

    
  end

  private
    def logged_in
      if(session[:user_id])
        return true
      else
        redirect_to main_path, alert: "Please login."
      end
    end

    def is_user
      if(session[:user_id] != @user.id)
        redirect_to main_path, alert: "Log in with wrong user"
      else
        return true
      end
    end

    def is_nuser
      if(session[:user_id].to_s != params[:id])
        redirect_to main_path, alert: "Log in with wrong user"
      else
        return true
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_formMain.html.erb
<%= simple_form_for(@user, method: :post, url: '/login') do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Login"  %>
  </div>
  <a href= <%=new_user_path%> class="btn btn-info btn-sm " tabindex="-1" role="button" >Sign up</a>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>


<%= link_to 'Back', "/feed/#{@user.id}" %>

app/views/users/feed.html.erb
<p id="notice"><%= notice %></p>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">UTwitter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/feed/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= new_post_path(:id=>session[:user_id])%> >Create Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= <%= edit_user_path(@user)%>>Edit profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<!--<%= link_to 'CreatePost', new_post_path(:id=>@user.id) %>-->
<!-- <table>
  <thead>
    <tr>
      <th>msg</th>      
      <th>time</th>
      <th colspan="2"></th>
    </tr>
  </thead> -->
  <% posts = @pfeed %>
  <div>
    <% posts.each do |post| %>
      <!-- <div>
      	<div>--------------------------</div>
        <%id = post.user_id  %>
        <%user = User.find_by(id: id)%>
        <div><%=  user.name%></div>
        <div><%= post.msg %></div>
        <div><%= post.updated_at %></div>
        <div>--------------------------</div>
      <div> -->
      <div class="card" style="width: 18rem;">
      <%id = post.user_id  %>
      <%user = User.find_by(id: id)%>
      <div class="card-body">
      <h5 class="card-title"><%=  user.name%></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= post.updated_at %></h6>
      <p class="card-text"><%= post.msg %></p>
      <%like = Like.find_by(post_id: post.id,user_id: session[:user_id] )%>
      <%if like == nil%>
      <a href= <%="/like/#{post.id}"%> class="btn btn-info btn-sm " tabindex="-1" role="button" >Like</a>
      <%else%>
      <a href= <%="/unlike/#{post.id}"%> class="btn btn-warning btn-sm " tabindex="-1" role="button" >Unlike</a>
      <%end%>
      <!-- Button trigger modal -->
      <button class="card-link xyz" data-bs-toggle="modal" data-bs-target="#exampleModal<%=post.id%>" data-like = '<%=post.get_user_like%>' >
      <%="Like: #{post.get_count_like}"%>
      </button>

      <!-- Modal -->


      </div>
      </div>
    <% end %>
  </div>
<div class="modal fade" id="likeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Total Likes</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id = "body">
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(".xyz").click(function(){
      var myModal = new bootstrap.Modal(document.getElementById('likeModal'), {})
      $(".modal-body").empty();
      const data = $(this).data("like");
      //$(".modal-body").text(data);
      for (let i = 0 ; i < data.length; i++) {
        $(".modal-body").append(`<a href="/profile/${data[i]}">${data[i]}</a><br>`);
      }
      myModal.show();
  })
</script>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table id= "myTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready( function () {
    $('#myTable').DataTable();
  });
</script>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/main.html.erb
<h1>Main</h1>

<%= render 'formMain', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>


<a href= <%=main_path%> class="btn btn-info btn-sm " tabindex="-1" role="button" >Back</a>

app/views/users/profile.html.erb
<p id="notice"><%= notice %></p>



<%name = params[:name]%>
<%@user = User.find_by(name: name)%>
<%pid = session[:user_id] %>
<%puser = User.find_by(id: pid)%>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">UTwitter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href= "/feed/<%=session[:user_id]%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= new_post_path(:id=>session[:user_id])%> >Create Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= <%= edit_user_path(puser)%>>Edit profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href= "http://localhost:3000/main">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<%follow = Follow.find_by(follower: @user.id,followee: pid )%>
<%if follow == nil%>
  <a href= <%="/follow/#{@user.id}"%> class="btn btn-info btn-sm " tabindex="-1" role="button" >Follow</a>
<%else%>
  <a href= <%="/unfollow/#{@user.id}"%> class="btn btn-warning btn-sm " tabindex="-1" role="button" >Unfollow</a>
<%end%>
<!-- <table>
  <thead>
    <tr>
      <th>msg</th>      
      <th>time</th>
      <th colspan="2"></th>
    </tr>
  </thead> -->

  <div>
    <%posts = @user.posts%>
    <%nposts = posts.sort{ |a,b| a.updated_at <=> b.updated_at}.reverse%>
    <% nposts.each do |post| %>
      <div class="card" style="width: 18rem;">
      <%id = post.user_id  %>
      <%user = User.find_by(id: id)%>
      <div class="card-body">
      <h5 class="card-title"><%=  user.name%></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= post.updated_at %></h6>
      <p class="card-text"><%= post.msg %></p>
      <%like = Like.find_by(post_id: post.id,user_id: session[:user_id] )%>
      <%if like == nil%>
      <a href= <%="/like/#{post.id}"%> class="btn btn-info btn-sm " tabindex="-1" role="button" >Like</a>
      <%else%>
      <a href= <%="/unlike/#{post.id}"%> class="btn btn-warning btn-sm " tabindex="-1" role="button" >Unlike</a>
      <%end%>
      <!-- Button trigger modal -->
      <button class="card-link" data-bs-toggle="modal" data-bs-target="#exampleModal<%=post.id%>">
      <%="Like: #{post.get_count_like}"%>
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal<%=post.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Total Likes</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%likeUser = post.get_user_like%>
              <%likeUser.each do |like| %>
                <a href="/profile/<%=like%>"><%=like%></a>
                <br>
              <%end%>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      </div>
      </div>
    <% end %>
  </div>


<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>