config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :follows
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main' ,to: 'users#main'
  post 'login' ,to: 'users#login'
  get 'feed/:id' ,to: 'users#feed'
  get 'profile/:name' ,to: 'users#profile'
  get 'profile/:name' ,to: 'users#profile'
  get 'follow/:id' ,to: 'follows#follow'
  get 'unfollow/:id' ,to: 'follows#unfollow'
  get 'like/:id' ,to: 'likes#like'
  get 'unlike/:id' ,to: 'likes#unlike'
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: %i[ show edit update destroy ]

  # GET /follows or /follows.json
  def index
    @follows = Follow.all
  end

  # GET /follows/1 or /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows or /follows.json
  def create
    @follow = Follow.new(follow_params)

    respond_to do |format|
      if @follow.save
        format.html { redirect_to @follow, notice: "Follow was successfully created." }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1 or /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to @follow, notice: "Follow was successfully updated." }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1 or /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to follows_url, notice: "Follow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def follow
    @follow = Follow.new(follower_id: params[:id], followee_id: session[:user_id])
    @follow.save
    redirect_to "/feed/#{session[:user_id]}"
  end

  def unfollow
    @follow = Follow.find_by(follower_id: params[:id], followee_id: session[:user_id])
    @follow.destroy
    redirect_to "/feed/#{session[:user_id]}"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follow_params
      params.require(:follow).permit(:follower_id, :followee_id)
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<%= simple_form_for(@follow) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :follower %>
    <%= f.association :followee %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Follows</h1>

<table id = "myTable">
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.follower_id %></td>
        <td><%= follow.followee_id %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script>
  $(document).ready( function () {
    $('#myTable').DataTable();
  });
</script>
<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @follow.follower_id %>
</p>

<p>
  <strong>Followee:</strong>
  <%= @follow.followee_id %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>